#!/bin/bash
#
# whouse
#
# chkconfig: - 99 01
# description: Reads EDesk Warehouse tapes.
# processname: whouse
# config: /etc/whouse.conf
# pidfile: /var/run/whouse.pid

# Source function library.
. /etc/init.d/functions

# Source an auxiliary options file if we have one, and pick up OPTIONS,
if [ -r /etc/whouse.conf ] ; then
	. /etc/whouse.conf
fi

whtaped=/usr/sbin/whtaped
[ -x ${whtaped} ] || exit 0

RETVAL=0

function start() {
        # Start daemons.
	prog=`basename ${whtaped}`
  echo -n $"Starting $prog: "
	daemon --user tomcat ${whtaped} $EDESK_SITE $WHOUSE_OPTIONS
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/whouse
	return $RETVAL
}

function stop() {
        # Stop daemons.
	prog=`basename ${whtaped}`
	echo -n $"Stopping $prog: "
	killproc ${whtaped}
	RETVAL=$?
	echo
  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/whouse
	return $RETVAL
}

# See how we were called.
case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    status)
        status ${whtaped}
	;;

    restart)
	stop
	start
	;;

    reload)
    	killproc ${whtaped} -HUP
	RETVAL=$?
	;;

    condrestart)
        if [ -f /var/lock/subsys/whouse ] ; then
            stop
            start
        fi
	;;
    *)
	echo $"Usage: $0 {start|stop|restart|status|condrestart}"
	RETVAL=1
esac

exit $RETVAL
